#!/bin/bash


export VERSION=
export MILESTONE=
export NEXT_MILESTONE=

export XAP_COMMIT_SHA=
export XAP_OPEN_COMMIT_SHA=

export JENKINS_HOST=
export JENKINS_PORT=
export JENKINS_USER=
export JENKINS_PASSWORD=
export WORKSPACE=/tmp/workspace

export XAP_NEWMAN_HOST=
export XAP_NEWMAN_USER=
export XAP_NEWMAN_PASSWORD=
export SSHPASS=$XAP_NEWMAN_PASSWORD

